version: 1.0.{build}
image: Visual Studio 2019
environment:
    nodejs_version: "22"
    GITHUB_TOKEN:
        secure: dfRaGCqPXIRBEzb3e/MgS1H9iKXi8nHCP/zgia2JCVt/mOa5lUjwjDQdXVvlanoe
        
install:
    - ps: Install-Product node $env:nodejs_version
    - yarn install
build_script:
    - yarn build
artifacts:
    - path: dist
      name: dist
on_success:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "appveyor@example.com"
  - git remote set-url origin https://%GITHUB_TOKEN%@github.com/PrekinII/Trello-js.git
  - yarn deploy
deploy:
  provider: GitHub
  auth_token:
    secure: dfRaGCqPXIRBEzb3e/MgS1H9iKXi8nHCP/zgia2JCVt/mOa5lUjwjDQdXVvlanoe
  tag: $(APPVEYOR_BUILD_VERSION)
  on:
    branch: main